### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/url-shortener#1]
Add a pull request template to the project.

**Comment by ak7550** [comment]
Hey @adityabisoi , I would like to work on the issue. Please assign this to me.

**Comment by adityabisoi** [comment]
Complete assigned ones first.

**Comment by prakhar1144** [comment]
@adityabisoi  will you please assign this to me.

**Comment by ak7550** [comment]
@adityabisoi  raised a PR of pull request template [created pull_request_template.md file #12](https://github.com/the-browser-toolbox/url-shortener/pull/12). Please check and let me know if any changes are required.
