### ISSUE TITLE
Fetch URL of current page

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/url-shortener#7]
Add script to fetch the URL of the website the user is currently on so that it cal be shortened.

To be done after issue #6 is resolved.

**Comment by has12zen** [comment]
Hi, I would Like to work on this part once issue #6 is resolved can you please assign this task to me

**Comment by adityabisoi** [comment]
@has12zen sure.

**Comment by has12zen** [comment]
hey can you please assign this issue now I want to submit a pull request also please check that out

**Comment by adityabisoi** [comment]
@has12zen Ok

**Comment by has12zen** [comment]
Can you merge the pull request or is there an issue?
