### ISSUE TITLE
Add linting and formatting

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/url-shortener#8]
For consistency in styling, linters, and code formatters are used. The most popular ones for JavaScript are `ESLint` and `Prettier`.
Add linting and formatting support to the project.

**Tip:** Use the configuration files and scripts at https://gitlab.com/adityabisoi/aossie-scholar

**Comment by ghost** [comment]
Can you assign me please.

**Comment by adityabisoi** [comment]
@maximilianschmelzer Go ahead:)

**Comment by ghost** [comment]
Just pushed something https://github.com/the-browser-toolbox/url-shortener/pull/10 :)
